### ISSUE TITLE
App opens in browser if action buttons in settings are clicked

### ISSUE THREAD

**Issue by one-step-behind** [Laverna/laverna-desktop#2]
If I click `Close`, `Save` or the backlink at the settings view the app opens in the browser. This is caused by [this line](https://github.com/Laverna/laverna-desktop/blob/master/app/WindowManager.js#L28) in WindowManager. It has to be `` `file://${__dirname}/dist` `` (backticks instead of single quotes and just two slashes instead of three (at least on MacOS - didn't tested this on another OS)).

**Comment by wwebfor** [comment]
It was fixed.
